### ISSUE TITLE
Add functions for read_initial_state and save_current_state

### ISSUE THREAD

**Issue by jmframe** [NOAA-OWP/lstm#14]
Short description explaining the high-level reason for the new issue.

## Current behavior
Only option to save and load the model states

## Expected behavior
save the state at some point
load in the saved state and start from there.

**Comment by madMatchstick** [comment]
Both serialization and deserialization are handled via `pickle`.  See sections 8 and 9 in [lstm_serialization_test.ipynb](https://github.com/NOAA-OWP/lstm/blob/master/lstm_serialization_test.ipynb).  
We can include functionalities under a single function definition(s) for convenience, yes.
Related Issue: put serialization example in a .py file #15

**Comment by madMatchstick** [comment]
> @madMatchstick Is this issue closed by the serialization work?

I believe so.  More specifically, via `pickle.dump()` and `pickle.load()` as seen in `lstm_serialization_test.py` [here](https://github.com/NOAA-OWP/lstm/blob/8d33cc9d0900984833ab0f311e932c9cc595e510/lstm/lstm_serialization_test.py#L96) & [here](https://github.com/NOAA-OWP/lstm/blob/8d33cc9d0900984833ab0f311e932c9cc595e510/lstm/lstm_serialization_test.py#L107).  Okay to close imho.
