### ISSUE TITLE
put serialization example in a .py file

### ISSUE THREAD

**Issue by jmframe** [NOAA-OWP/lstm#15]
Short description explaining the high-level reason for the new issue.

## Current behavior
in a notebook, can't run from terminal

## Expected behavior
run from terminal

**Comment by madMatchstick** [comment]
> Short description explaining the high-level reason for the new issue.
> 
> ## Current behavior
> in a notebook, can't run from terminal
> 
> ## Expected behavior
> run from terminal

The jupyter notebook, [lstm_serialization_test.ipynb](https://github.com/NOAA-OWP/lstm/blob/master/lstm_serialization_test.ipynb), seems to be fully functional in the browser (via `jupyterlab`).  We can, and should, develop a parallel python script demonstrating & validating the fundamentals of serialization, similar to the  jupyter notebook. 

Note:  Current documentation does not cover serialization.   We will need to update/include instructions for both relatable scripts (ipynb & py).  

@SnowHydrology @peckhams - Our bmi c-based formulation models separate serialization, or more specifically `owp-bmi-enhance`, development into a separate branch outside of `master`. Should we do the same here?

**Comment by madMatchstick** [comment]
>Our bmi c-based formulation models separate serialization, or more specifically owp-bmi-enhance, development into a separate branch outside of master. Should we do the same here?

Per conversation, we will keep all notebook files.  Need to document
