### ISSUE TITLE
Temperature should actually be in kelvin

### ISSUE THREAD

**Issue by jmframe** [NOAA-OWP/lstm#22]
Short description explaining the high-level reason for the new issue.

## Current behavior
BMI claims it wants temperature in Kelvin, but the model actually wants Celcius

## Steps to replicate behavior (include URLs)

1. Either add in a conversion,
2. or change the BMI unit

**Comment by SnowHydrology** [comment]
@hellkite500 I want to confirm your PR #23  closes this. [Line 110](https://github.com/NOAA-OWP/lstm/blob/8d33cc9d0900984833ab0f311e932c9cc595e510/lstm/bmi_lstm.py#L110) in `bmi_lstm.py` suggests yes.

**Comment by hellkite500** [comment]
4f36cc304a0a321c1d5a48c0891e1e8e1ce69dfe gets the correct Celicus units described for the input.
