### ISSUE TITLE
Ensure correct implementations for getter and setter functions

### ISSUE THREAD

**Issue by robertbartel** [NOAA-OWP/lstm#24]
There are some issues with the current implementations of the getter and setter functions.  These are things that don't properly adhere to the BMI specification. 

## `get_value`
First, the signature of this function isn't correct.  Right now it is:
```Python
def get_value(self, var_name):
```
But in the specification it is defined as:

```Python
def get_value(self, name: str, dest: np.ndarray) -> np.ndarray:
```

This directly prevents it from behaving correctly.   It is expected to copy the values of the desired variable into the (already appropriately initialized) `dest` NumPy array.

Also related, the function right now is returning the backing NumPy array from `get_value_ptr`.  It probably needs to return `dest` once that's added.  Regardless, it shouldn't return a direct reference to the backing variable.

## `get_value_at_indices`
This will need to be modified after changes to `get_value`.  I think it's also making an unnecessary copy of the entire backing NumPy array, before then copying the right individual values into the supplied `dest` array.

## `set_value`
This function has its required second parameter for containing the values to set, but appears to makes invalid assumptions that are based on something beyond the BMI specification: e.g., that it is a singleton array.   That in particular also seems to be contradicted by there being valid `get_value_at_indices` and `set_value_at_indices` functions (i.e., why not raise an exception to indicate there is only index 0, and thus the `at_indices` functions are unnecessary and inappropriate?).

## `set_value_at_indices`
Again, this seems to try to account for the possibility of singleton arrays in ways that contradict needing `at_indices` functions, and that aren't strictly consistent with BMI.

**Comment by robertbartel** [comment]
Note that this assessment assumes the inclusion of #23.

**Comment by madMatchstick** [comment]
Be aware that this change effects the following bmi functions,
```
  get_var_itemsize()
  get_value()
  get_value_ptr()
  set_value_at_indices()
  get_value_at_indices()
```
Any build/run scripts (py or ipynb) would also need to be updated for these five function calls.\

Useful links related to post:
- heat example:[ bmi_heat.py](https://github.com/csdms/bmi-example-python/blob/master/heat/bmi_heat.py#L201)
- bmi specification: [bmi.py](https://github.com/csdms/bmi-python/blob/master/bmipy/bmi.py#L337)
- best practices: [csdms doc](https://bmi.readthedocs.io/en/latest/bmi.best_practices.html)
