### ISSUE TITLE
Using newly trained lstm models

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/lstm#26]
A [scaler file](https://github.com/NOAA-OWP/lstm/blob/e8891f45939c09e943c9e728dfa2e9c1513834ef/bmi_lstm.py#L259) is required in order to use a lstm model other than the ones saved in the repository.  @jmframe where do these get generated from?  Wasn't clear in the neuro hydrology if it produces this.  Can you provide any guidance on the steps to bring a new lstm model for inclusion?

**Comment by jmframe** [comment]
Yes, it is created by NeuralHydrology when the training data are compiled. It looks like newer versions use a YML file, instead of a pickle file, which is probably better: https://github.com/neuralhydrology/neuralhydrology/blob/1ff36ea8c8eff99ad25fa0f56f0119acbc9e6799/neuralhydrology/datasetzoo/basedataset.py#L193

**Comment by jmframe** [comment]
Just to make sure, you are training a new model with NeuralHydrology? If not, that is okay too, just need to know.

**Comment by hellkite500** [comment]
Just trying to get some people familiar with the entire process, including training a model and then operating it here.  @madMatchstick worked through training a model using neuralhydrology but didn't find the scaler file to try using it with the lstm bmi.  It may be that we were just looking for a pickle file instead of the yaml file, haha.  I browsed through the code and found the function you referenced, but wasn't sure if it required some custom option to ensure it got dumped or not.  Thanks for the quick reply!

**Comment by jmframe** [comment]
Yeah, no problem. Feel free to ask away. I'm happy to help, and I would like to stay involved, if possible. Where are you doing the training? What machine, what dataset?

**Comment by madMatchstick** [comment]
Thanks @hellkite500 & @jmframe for clarification on scaler pickle vs yaml file.  

I was able to adjust `get_training_configurations()` and `get_scaler_values()` for proper yml read-in. 
However, I am still getting a runtime error during `bmi.initialize` , but very possible that the newly trained file(s) are garbage.
Current model's `batch_size` and `inputs` are correct; `([256, 35])`. 
When manually matching the model "shape" to the apparent weights shape `([256, 128])`, the [forward-pass](https://github.com/NOAA-OWP/lstm/blob/e8891f45939c09e943c9e728dfa2e9c1513834ef/nextgen_cuda_lstm.py#L23) fails at  `input_view`.
I'm generating another simple sample training set to test, and will leave this issue open for now.

```
RuntimeError: Error(s) in loading state_dict for Nextgen_CudaLSTM:
        size mismatch for lstm.weight_ih_l0: copying a param with shape torch.Size([256, 128]) 
        from checkpoint, the shape in current model is torch.Size([256, 35]).
```

Curious @jmframe - how much of your focus was on training and evaluating via [neuralhydrology](https://neuralhydrology.readthedocs.io/en/latest/usage/quickstart.html#training-a-model)? I do have a couple (configuration, etc.) questions if you're up for it and have the time to spare?

Oh and I'm using `hourly_camels_us` dataset but only over a handful of basins as I'm just running things on my work laptop.

**Comment by jmframe** [comment]
@madMatchstick okay, this should be an easy fix. You should have a NeuralHydrology configuration file that the BMI is reading in, correct? Can you send me a link or paste it here? What inputs are you trying to use?

All the training and evaluation was done with NeuralHydrology. And it was extensive. 

Yes, let's meet during an afternoon next week.
