### ISSUE TITLE
csdms standard name for precip

### ISSUE THREAD

**Issue by madMatchstick** [NOAA-OWP/lstm#35]
Reminder to confirm appropriate term for input var precip; `atmosphere_water__time_integral_of_precipitation_mass_flux` vs `atmosphere_water__liquid_equivalent_precipitation_rate` as mentioned/adjusted in PR #34.

**Comment by SnowHydrology** [comment]
@madMatchstick Did this one ever get sorted?

**Comment by SnowHydrology** [comment]
Closed by #34
