### ISSUE TITLE
Broken link to example configuration file

### ISSUE THREAD

**Issue by aaraney** [NOAA-OWP/lstm#37]
This link is broken. It looks like the link just needs to be updated to `../trained_neuralhydrology_models/hourly_all_attributes_and_forcings/config.yml`.

https://github.com/NOAA-OWP/lstm/blob/63116cc6a6bbdb5537868f20ff55cc326795b570/bmi_config_files/README.md?plain=1#L6

For longevity, it might be best to use a permalink though:

https://github.com/NOAA-OWP/lstm/blob/63116cc6a6bbdb5537868f20ff55cc326795b570/trained_neuralhydrology_models/hourly_all_attributes_and_forcings/config.yml

Im happy to open a PR to fix this, just let me know which one you all prefer.

**Comment by SnowHydrology** [comment]
@aaraney, fix and PR away!
